apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: database
    spec:
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres:9.6.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
          - name: postgres-volume
            mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-volume
        hostPath:
          path: /data/postgresvolume
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails
  labels:
    app_name: produciton
    app_version: "0.1"
spec:
  selector:
    matchLabels:
      app_name: produciton
      app_version: "0.1"
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      name: rails
      labels:
        app_name: produciton
        app_version: "0.1"
    spec:
      containers:
      - name: rails
        image: dailydrip/produciton:master
        env:
        - name: PGHOST
          value: "postgres"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
