apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  template:
    metadata:
      name: migrations
    spec:
      containers:
      - name: migrations
        image: dailydrip/produciton:master
        args: ["rake db:setup"]
        env:
        - name: PGHOST
          value: postgres
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
      restartPolicy: Never
