kind: Service
apiVersion: v1
metadata:
  name: produciton
spec:
  selector:
    app_name: produciton
    tier: app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tier: database
spec:
  ports:
  - port: 5432
  selector:
    tier: database
